server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registration
    username: root
    password: Charbouli12019***
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: rheahamdar@gmail.com
    password: vpys tggv zlap xpui
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
